# Generated by Django 3.1.8 on 2021-09-29 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('type', models.IntegerField(choices=[(1, 'Have'), (2, 'Interest')], help_text='보유 구분 1: 보유 2: 관심')),
                ('amount', models.BigIntegerField(default=0, help_text='투자금액')),
                ('is_delete', models.BooleanField(default=False, help_text='삭제여부')),
                ('create_date', models.DateTimeField(default=None, help_text='생성날짜', null=True)),
                ('portfolio', models.ForeignKey(help_text='포트폴리오', on_delete=django.db.models.deletion.PROTECT, related_name='user_portfolio', to='portfolio.portfolioinfo')),
                ('user', models.ForeignKey(help_text='회원', on_delete=django.db.models.deletion.PROTECT, related_name='my_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_my_portfolio',
            },
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('number', models.IntegerField(help_text='거래 수')),
                ('price', models.DecimalField(decimal_places=2, help_text='거래 가격', max_digits=19)),
                ('trade_type', models.IntegerField(choices=[(1, 'Buy'), (2, 'Sell')], help_text='거래구분, 1: 매수 2: 매도')),
                ('stock', models.ForeignKey(help_text='종목', on_delete=django.db.models.deletion.PROTECT, to='stocks.basicinfo')),
                ('user', models.OneToOneField(help_text='회원', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_trade_log',
            },
        ),
        migrations.CreateModel(
            name='MyStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('type', models.IntegerField(choices=[(1, 'Have'), (2, 'Interest')], help_text='보유 구분 1: 보유 2: 관심')),
                ('stock', models.ForeignKey(help_text='종목', on_delete=django.db.models.deletion.PROTECT, related_name='userHold', to='stocks.basicinfo')),
                ('user', models.ForeignKey(help_text='회원', on_delete=django.db.models.deletion.PROTECT, related_name='myHold', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_my_stocks',
            },
        ),
        migrations.CreateModel(
            name='MyPortfolioStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('percentage', models.FloatField(default=0, help_text='비중')),
                ('hold_number', models.IntegerField(default=0, help_text='보유 주 수')),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, help_text='구매 시 단가', max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='구매 시 총 액', max_digits=12)),
                ('portfolio', models.ForeignKey(help_text='해당 내 포트폴리오', on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='member.myportfolio')),
                ('stock_code', models.ForeignKey(help_text='종목코드', on_delete=django.db.models.deletion.PROTECT, related_name='my_portfolio', to='stocks.basicinfo', to_field='code')),
            ],
            options={
                'db_table': 'user_my_portfolio_stocks',
            },
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['-created_at'], name='user_trade_log_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='mystocks',
            index=models.Index(fields=['user', 'type'], name='user_my_stocks_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='myportfoliostocks',
            index=models.Index(fields=['portfolio', 'stock_code', '-created_at'], name='user_my_por_portfol_f64532_idx'),
        ),
        migrations.AddIndex(
            model_name='myportfolio',
            index=models.Index(fields=['user', 'type'], name='user_my_port_user_type_idx'),
        ),
    ]
