# Generated by Django 3.1.8 on 2021-09-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('name', models.CharField(help_text='통화 이름', max_length=30)),
                ('code', models.CharField(help_text='통화 코드', max_length=3, unique=True)),
                ('number', models.IntegerField(help_text='통화 번호')),
                ('is_use', models.BooleanField(default=True, help_text='사용여부')),
            ],
            options={
                'db_table': 'common_currency',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('name', models.CharField(help_text='주식 시장명', max_length=30)),
                ('code', models.CharField(help_text='주식 시장 코드', max_length=10, unique=True)),
                ('is_use', models.BooleanField(default=True, help_text='사용여부')),
            ],
            options={
                'db_table': 'common_market',
            },
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['name', 'is_use'], name='common_market_name_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['is_use'], name='common_market_is_use_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['name', 'is_use'], name='common_currency_name_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_use'], name='common_currency_is_use_idx'),
        ),
    ]
